gui:
  name: "Квестовик"
  size: 54
  buttons:
    info-quest:
      slot: 45
      material: BOOK
      lore:
        - "§7Это NPC, который выдаёт задания"
        - "§7и награды за исследование мира."
        - "§7За выполнение заданий вы получаете"
        - "§7уникальные бонусы и ресурсы."
        - ""
        - "§eКак получать бонусы?"
        - "§7За опыт открываются новые уровни:"
        - "§7скорость, удача, ночное зрение и др."
        - ""
        - "§eКак зарабатывать опыт?"
        - "§7Опыт даётся за активность в мире:"
        - "§7- Исследование территорий"
        - "§7- Добыча редких ресурсов"
        - "§7- Встречи с мобами"
        - "§7- Выполнение достижений"

    info-stats:
      slot: 53
      material: PAPER

    grayPanel:
      material: GRAY_STAINED_GLASS_PANE
      slots:
        - 9
        - 10
        - 11
    orangePanel:
      material: ORANGE_STAINED_GLASS_PANE
      slots:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 46
        - 47
        - 48
        - 49
        - 50
        - 51
        - 52

  quests:
   material: BLACK_STAINED_GLASS_PANE
   slots:
     - 36
     - 27
     - 18
     - 9
     - 10
     - 11
     - 20
     - 29
     - 38
     - 39
   quest1:
     name: "§6Дом Странника"
     lore:
       - "§7Каждый мир враждебен,"
       - "§7и лишь стены, возведённые твоими руками,"
       - "§7могут даровать покой."
       - ""
       - "§fВозведи надёжное убежище,"
       - "§fчтобы вновь найти свет в темноте."

   quest2:
     name: "§6Огненный повар"
     lore:
       - "§7Огонь — друг выжившего,"
       - "§7он дарует силу тем, кто умеет ждать."
       - ""
       - "§fПриготовь пищу на пламени,"
       - "§fи насыть тело, укрепив дух."

   quest3:
     name: "§6Добытчик редкостей"
     lore:
       - "§7Мир хранит тайны глубоко внутри."
       - "§7Не каждый осмелится искать."
       - ""
       - "§fДобудь камни и кристаллы,"
       - "§fкоторых не коснулась дневная звезда."

   quest4:
     name: "§6Зверолов"
     lore:
       - "§7В каждом измерении свои стражи."
       - "§7Кто-то рычит, кто-то шипит, кто-то парит."
       - ""
       - "§fДокажи, что ты способен понять зверя,"
       - "§fи приручи его ярость."

   quest5:
     name: "§6Оружейник"
     lore:
       - "§7Металл туп без чар."
       - "§7Вложи в сталь дыхание магии."
       - ""
       - "§fЛишь тогда клинок станет продолжением воли,"
       - "§fа кирка — проводником силы."

   quest6:
     name: "§6Мостостроитель"
     lore:
       - "§7Между тобой и гибелью — лишь пустота."
       - "§7Но рука мастера способна построить путь."
       - ""
       - "§fВозведи мост через мрак,"
       - "§fи свяжи берега разных миров."

   quest7:
     name: "§6Хранитель огня"
     lore:
       - "§7Тьма жадно пожирает надежду."
       - "§7Но свет — вечный противовес её власти."
       - ""
       - "§fРазожги десять источников огня,"
       - "§fи стань хранителем света во мраке."

   quest8:
     name: "§6Кладоискатель"
     lore:
       - "§7Глубоко в недрах и руинах,"
       - "§7враждебные земли прячут сокровища."
       - ""
       - "§fОтыщи сундук в заброшенной структуре,"
       - "§fи прикоснись к богатствам древних."

   quest9:
     name: "§6Охотник за головами"
     lore:
       - "§7Не каждый трофей — оружие."
       - "§7Иногда он лишь доказательство силы."
       - ""
       - "§fДобудь редкий дроп у врага,"
       - "§fи укрась путь победы страшным знаком."

   quest10:
     name: "§5Охотник на драконью тень"
     lore:
       - "§7Есть лишь один враг,"
       - "§7что бросает тень на весь мир."
       - ""
       - "§fСразись с §5Драконом Края§f,"
       - "§fи выйди победителем, не пав ни разу."
       - ""
       - "§7Лишь тот, кто устоял перед вечной тьмой,"
       - "§7достоин называться героем."
