gui:
  name: "Квестовик"
  size: 54
  buttons:
    info-quest:
      slot: 45
      material: BOOK
      lore:
        - "§7Это NPC, который выдаёт задания"
        - "§7и награды за исследование мира."
        - "§7За выполнение заданий вы получаете"
        - "§7уникальные бонусы и ресурсы."
        - ""
        - "§eКак получать бонусы?"
        - "§7За опыт открываются новые уровни:"
        - "§7скорость, удача, ночное зрение и др."
        - ""
        - "§eКак зарабатывать опыт?"
        - "§7Опыт даётся за активность в мире:"
        - "§7- Исследование территорий"
        - "§7- Добыча редких ресурсов"
        - "§7- Встречи с мобами"
        - "§7- Выполнение достижений"

    info-stats:
      slot: 53
      material: PAPER

    grayPanel:
      material: GRAY_STAINED_GLASS_PANE
      slots:
        - 9
        - 10
        - 11
    orangePanel:
      material: ORANGE_STAINED_GLASS_PANE
      slots:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 46
        - 47
        - 48
        - 49
        - 50
        - 51
        - 52