name: QuestPlugman
version: '1.0-SNAPSHOT'
main: traiwy.questPlugman.QuestPlugman
api-version: '1.20'
commands:
  mineskills:
    usage: mineskills
  quest:
    usage: quest
  firstquest:
    usage: firstquest